### PR TITLE
fix: add testID back to credential card component

### PR DESCRIPTION
**Pull request by amanji**
# Summary of Changes

`testID` was removed with recent credential branding feature. This PR adds it back.

# Related Issues

#413 

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [ ] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [ ] Updated documentation as needed for changed code and new or modified features;
- [ ] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Review by nodlesh — COMMENTED** [review]
Thanks for this.
I do notice that we are changing CredentialIssued to CredentialCardFooter and CredentialIssuer to CredentialCardHeader, I'm assuming this is on purpose to support what is coming next. 
Also noticed there is no testID for CredentialVersion as it use to be, this is replaced with?

**Comment by amanji** [comment]
We no longer display the credential version in the card. So I removed that testID. The credential header contains both the issuer name/logo and the credential name so the testID was generalized to CredentialHeader. The footer was likewise generalized to account for issued date and revoked date (coming soon).

**Comment by amanji** [comment]
It just made sense to name the testIDs based on what the sections are rather than the content they have. With OCA I don't think there will be much if any restrictions over the data displayed.

**Comment by nodlesh** [comment]
Sounds good. Thanks for the explanation.

**Review by nodlesh — APPROVED** [review]

**Review by cvarjao — APPROVED** [review]
LGTM

**Pull request merged**
