### PR TITLE
feat: add pt-BR hour format

### PR DESCRIPTION
**Pull request by CarolineLCa**
# Summary of Changes

Adding pt-BR format hour (24h) when this language is selected.

# Related Issues

 N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [X] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [X] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [X] Updated documentation as needed for changed code and new or modified features;
- [X] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Review by bryce-mcmath — APPROVED** [review]

**Comment by thiagoromanos** [comment]
Wouldn't it be better if this format be a i18n key? Many apps that support pt-BR uses 12 hour format, so 24 hours is not a strict rule. Checking device's configuration would be nice (https://github.com/steffenagger/react-native-device-time-format)

**Comment by bryce-mcmath** [comment]
@CarolineLCa can you implement the above as an alternative to this change?

**Comment by CarolineLCa** [comment]
> @CarolineLCa can you implement the above as an alternative to this change?

@thiagoromanos  @bryce-mcmath 

I have checked this dependence and tried to implement it, but  `DeviceTimeFormat.is24HourFormat()` is an async function while our `formatTime()` is non-async so this change would not only affect this function but also a lot of other components that use it. 

Captura de Tela 2023-10-04 às 06 39 20

**Comment by thiagoromanos** [comment]
> > @CarolineLCa can you implement the above as an alternative to this change?
> 
> @thiagoromanos @bryce-mcmath
> 
> I have checked this dependence and tried to implement it, but `DeviceTimeFormat.is24HourFormat()` is an async function while our `formatTime()` is non-async so this change would not only affect this function but also a lot of other components that use it.
> 
> Captura de Tela 2023-10-04 às 06 39 20

Gonna open an issue for that. It'll need a lot of refactoring indeed, but it would be great to have the time format matching the device's format.

**Comment by thiagoromanos** [comment]
Opened the issue #986 for that.

**Pull request merged**
