### PR TITLE
fix: iOS app permissions

### PR DESCRIPTION
**Pull request by MosCD3**
# Summary of Changes

iOS 14+ uses local network permissions at app start which triggers permissions package to start, incorrectly configured Podfile and outdated package version cause an exception trigger at iOS app startup
Updated `react-native-permissions` package and added configuration in Podfile
Also tested Android to make sure updating package doesn't affect the flow

IMG_0272

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [X] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [ ] Updated documentation as needed for changed code and new or modified features;
- [ ] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

### CODE REVIEW

**Comment by cvarjao** [comment]
@MosCD3 , can't we use the [reactNativePermissionsIOS.json ](https://github.com/hyperledger/aries-mobile-agent-react-native/blob/main/packages/legacy/app/reactNativePermissionsIOS.json) configuration file instead of changing the cocoa pod configuration file?

**Comment by jleach** [comment]
This may be unique to your development environment. I don't see this. I do some times see, when the app starts, it ask for permission to use the network. I just answer yes and it seems to work fine. I think this is proper behaviour for iOS though.

**Comment by MosCD3** [comment]
keep it a bit until I retest if not a solution I will close it

**Comment by jleach** [comment]
@MosCD3 I was running Bifold the other day and ran into this problem. I think it may be needed here. Are you able to fix the conflicts so it can be merged?

**Comment by MosCD3** [comment]
Yes sure, will do that

**Review by jleach — APPROVED** [review]

**Pull request merged**
