### PR TITLE
Revoked credential status

### PR DESCRIPTION
**Pull request by amanji**
# Summary of Changes

* Adds mechanism to temporarily track revoked credentials until hooks are updated to emit when credential record metadata changes.
* Adds styling to indicate revoked status in credential list and detail pages.
* Adds an info message to indicate further action for a revoked credential in the detail page.
* Refactors store to use best practices in naming conventions (adopted by the redux community)

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [ ] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [ ] Updated documentation as needed for changed code and new or modified features;
- [ ] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Comment by jleach** [comment]
@amanji I think this has the changes from other PRs so I'll hold off until the context PR is merged.

**Comment by amanji** [comment]
This PR is the start of the context refactoring so it needs to go in first

**Comment by amanji** [comment]
This PR is the start of the context refactoring so it needs to go in first

**Review by jleach — APPROVED** [review]
@amanji LGTM. Is this a temporary fix waiting on support in AFJ or do you think it'll be permanent in the wallet?

**Comment by amanji** [comment]
100% a temp fix. Down the road I expect that this will all be handled by the revocation message handler in AFJ with the state reflected in the credential record metadata. I have purposely added `FIXME`s to ensure the code is removed once the feature is supported.

**Comment by amanji** [comment]
100% a temp fix. Down the road I expect that this will all be handled by the revocation message handler in AFJ with the state reflected in the credential record metadata. I have purposely added `FIXME`s to ensure the code is removed once the feature is supported.

**Pull request merged**
