### PR TITLE
Feature/localization

### PR DESCRIPTION
**Pull request by nbAmit**
# Summary of Changes

- Implemented the localization features, Added two new language French or Hindi
- Added title for each screen to remove screen name dependency
- User can easily change the app language from settings screen
- Refactored Proof Request class name

[Video](https://github.com/nbAmit/Screenshots/blob/master/Bifold-localization.gif)

# Related Issues

#90 

# Pull Request Checklist

This is just a reminder about the most common mistakes. Please make sure that you tick all _appropriate_ boxes. But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this).
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components.
- [x] Run prettier: `npm run style-format`
- [x] Updated **documentation** for changed code and new or modified features.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Comment by TimoGlastra** [comment]
Hi @nbAmit,

Thanks for this! This PR is very similar to the work @jleach has been doing. I think we should take the best of both PRs and merge those together.

Currently there is already support for localization using i18next, and https://github.com/hyperledger/aries-mobile-agent-react-native/pull/115 adds the missing lacalization strings.

Maybe we can pick the following from your PR:
- the settings screen to switch language 
- The json structure of the localization with translations for French, English and Hindi

The current localization already has the required setup with typescript integration so it would be good to use that I think

It looks like your branch is out of date quite a bit (still contains aries-hooks). Could you update your branch?

@jleach what are your thoughts on this?

**Comment by nbAmit** [comment]
Thanks @TimoGlastra I will take the latest code, I and @jleach will coordinate on this part and update the PR
@jleach What do you suggest how we can combine our changes?

**Comment by jleach** [comment]
@nbAmit There is some good stuff in your PR but now that i18n is already implemented I suspect you will need to stash these changes in a branch and make any changes to a new updated `main` branch.  Other than that I agree with what @TimoGlastra said above.

**Comment by jleach** [comment]
@TimoGlastra @nbAmit Should we add the French and Hindi translations? They're valuable but what will developers do who don't speak those languages who need to add or change text? Just add the English versions in the translations and wait another developer to contribute the translation?

**Comment by TimoGlastra** [comment]
Good question @jleach. I agree with your suggestion to use english as a fallback languages. I would say we have officially supported languages (for now just english) and non-official languages. Official languages must be updated for every PR, while non-official languages can fall back to english.

@nbAmit would you be willing to maintain the French / Hindi languages? I think it would be good to have a maintainer for every language.

**Comment by nbAmit** [comment]
@TimoGlastra Sure I will take care of  French and Hindi languages translations. @jleach Now I can see you PR is marge to the master so I will take pull form that I will add the setting screen and translation files.
Thanks you guys for your support

**Comment by jleach** [comment]
@nbAmit We talked through how to deal with additional translations at yesterdays user group meeting. I don't recall if we came up with a good strategy for doing so. The challenge is, for those of us who don't speak Hindi we won't be able to change / update text. The more languages we add the harder it will become to maintain them. I think for now we'll just go with English as the default and let others implement the translations they need before shipping a product.

**Comment by nbAmit** [comment]
I will raise new PR with based your suggestions

**Pull request closed without merging**
