### PR TITLE
Fix/aries hooks

### PR DESCRIPTION
**Pull request by Przytua**
# Summary of Changes

* Fixed a bug throwing `Invalid hook call` related to two copies of `React` running in the app
* Fixed default mediator config to work as previous version
* Fixed state usage in `aries-hooks` to properly update on events
* Brought back `PollingInboundTransporter` to receive messages
* Fixed `Intl` error on Contacts screen
* Other minor fixes

# Pull Request Checklist

This is just a reminder about the most common mistakes. Please make sure that you tick all _appropriate_ boxes. But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this).
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components.
- [x] Run prettier: `npm run style-format`
- [x] Updated **documentation** for changed code and new or modified features.

Tested with .env file containing
```
MEDIATOR_URL=https://mediator.animo.id
GENESIS_URL=http://dev.greenlight.bcovrin.vonx.io/genesis
```

and using Faber demo Agent from the `https://github.com/hyperledger/aries-cloudagent-python` repository ran on `https://labs.play-with-docker.com` with
```
LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber
```

I was able to receive protected text message:
```
 DEBUG  DEBUG: Agent Aries Bifold received message
 INFO  INFO: Received message with type 'https://didcomm.org/messagepickup/1.0/batch' from connection 82a71d4a-f236-4672-80cf-2bbe4e811554 (Animo Mediator) {
  "@type": "https://didcomm.org/messagepickup/1.0/batch",
  "@id": "dad39efc-3f06-4904-939a-a144339ab009",
  "messages~attach": [
    {
      "id": "a36429da-a701-4843-9370-e2a5b4edead4",
      "message": {
        "protected": "eyJlbmMiOiJ4Y2hhY2hhMjBwb2x5MTMwNV9pZXRmIiwidHlwIjoiSldNLzEuMCIsImFsZyI6IkF1dGhjcnlwdCIsInJlY2lwaWVudHMiOlt7ImVuY3J5cHRlZF9rZXkiOiJtaTJqOExKbC1sdXlRM1V2TWlJbFl1amgzS3lXRExITVpHQjBwbDZCQ3FNYjhobnZMcGJIaXFhTFR5cDV4MGgxIiwiaGVhZGVyIjp7ImtpZCI6Ijd3ZjI5OXVmc3c0QUF4d0hmSnYyaU51TDNndXA5cVF2VGlINVFNc1R4QVBIIiwiaXYiOiI5VDFaRnpnZUtIeUNxYzZQM05fMTY1dHZNYThVdFJqUyIsInNlbmRlciI6IjV0ZlhtWFpOZmlpYUpYelNBUWpOV1g1ZGhpMklQZGNlTndHQXZRYzJ2RFBEYlI5Ung4eHM0U2lSbWIyUlVWaXJNN0wwTU9CNlEzOVYyemkwTXBXam9kSm5KTllyalpJT3FhMFpHVTIxbTBlZWRueUF2SURnV3lsRHhnPT0ifX1dfQ==",
        "iv": "JoRQTP8UH7r5n9Ze",
        "ciphertext": "FzQZYetyXrmxKoc05wtlbenZahB5lNq_txjmt7Gldqcf0FR86v8mmLk1s5XdhTCEnz9ZXeFyA1QxhcZ10CrSG18949DcloUvFGNipt9eVFkdC00doqgrBLjmrpffPLGtnyQ1AKmXsQbU5tZrzsQN1Vt0JLdwLtfMgA12mU--9HR6iCT-A-Chhno2UkTRBiCqRkRdebD6jh5w0VsSUC5cGoKkwxtLJxOzW4Xo6xKo6yJo2TJCiPcffcI=",
        "tag": "V5IkDz6MUgrSWttXDu_LMA=="
      }
    }
  ]
}
```
and credentials offer, although this message type is not yet supported:
```
ERROR  AriesFrameworkError: No handler for message type "https://didcomm.org/issue-credential/2.0/offer-credential" found, js engine: hermes
```
Anyway, the connection is working properly.

### CODE REVIEW

**Comment by manghuli** [comment]
Thanks for seeing those errors with the scanner and fixing those! From what I can tell with your changes, you're using an older version of AFJ that requires those changes. Please update that and your mediator to use one that supports coordinate mediation like the one below. That should negate a lot of your changes and make more sense 

`MEDIATOR_URL=http://mediator3.test.indiciotech.io:3000/?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiYjE5YTM2ZjctZjhiZi00Mjg2LTg4ZjktODM4ZTIyZDI0ZjQxIiwgInJlY2lwaWVudEtleXMiOiBbIkU5VlhKY1pzaGlYcXFMRXd6R3RtUEpCUnBtMjl4dmJMYVpuWktTU0ZOdkE2Il0sICJzZXJ2aWNlRW5kcG9pbnQiOiAiaHR0cDovL21lZGlhdG9yMy50ZXN0LmluZGljaW90ZWNoLmlvOjMwMDAiLCAibGFiZWwiOiAiSW5kaWNpbyBQdWJsaWMgTWVkaWF0b3IifQ==`

**Comment by Przytua** [comment]
> Thanks for seeing those errors with the scanner and fixing those! From what I can tell with your changes, you're using an older version of AFJ that requires those changes. Please update that and your mediator to use one that supports coordinate mediation like the one below. That should negate a lot of your changes and make more sense
> 
> `MEDIATOR_URL=http://mediator3.test.indiciotech.io:3000/?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiYjE5YTM2ZjctZjhiZi00Mjg2LTg4ZjktODM4ZTIyZDI0ZjQxIiwgInJlY2lwaWVudEtleXMiOiBbIkU5VlhKY1pzaGlYcXFMRXd6R3RtUEpCUnBtMjl4dmJMYVpuWktTU0ZOdkE2Il0sICJzZXJ2aWNlRW5kcG9pbnQiOiAiaHR0cDovL21lZGlhdG9yMy50ZXN0LmluZGljaW90ZWNoLmlvOjMwMDAiLCAibGFiZWwiOiAiSW5kaWNpbyBQdWJsaWMgTWVkaWF0b3IifQ==`

@NeilSMyers I've added fetching of invitation from the `/invitation` endpoint (so `http://mediator3.test.indiciotech.io:3000/invitation` in this case). Not sure if this is a good approach, but I tested it with AFJ from latest master, and was working properly. This way the `.env` file can be used the same way as before, and there's no need to copy this long invitation url, just the hostname.

**Comment by Przytua** [comment]
Ah, sorry, you might be right, I was actually testing it with a public mediator, not my own. Anyway it was a one that wasn't working with old version of this demo app due to mediation changes. I'll test this tomorrow with one set up with latest master code of AFJ to make sure it works properly.

**Comment by Przytua** [comment]
Tested it now with AFJ mediator from latest master and it's working properly

**Comment by manghuli** [comment]
These issues were addressed separately. Thank you very much for your contributions!

**Pull request closed without merging**
