### PR TITLE
chore: convert cicd to use yarn

### LINKED ISSUE #637: Update CI/CD pipelines to use yarn
Now that the project is migrated to yarn we need to update the CI/CD workflows to use it.

### PR DESCRIPTION
**Pull request by jleach**
# Summary of Changes

Minor changes to the CICD workflows for iOS and Android so they use yarn.

# Related Issues

Fixes #637 

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Review by cvarjao — CHANGES_REQUESTED** [review]
I think all changes are already in place. If there is anything missing, please update your fork, and resolve conflicts

**Comment by jleach** [comment]
@cvarjao Fixed. I was a bit out of date so I've brought in the updates. I've left one notable change in place: I don't think we need the custom action to setup node any more. By using v2 or better of the [action](https://github.com/actions/setup-node) we can just specify `cache: "yarn"` and forgo all the custom cache logic.

**Comment by cvarjao** [comment]
> @cvarjao Fixed. I was a bit out of date so I've brought in the updates. I've left one notable change in place: I don't think we need the custom action to setup node any more. By using v2 or better of the [action](https://github.com/actions/setup-node) we can just specify `cache: "yarn"` and forgo all the custom cache logic.

I would prefer if we keep the custom node setup, it still wraps the setup and we don't need to do a bunch of copy/paste, and repeat the wring node version etc

**Comment by jleach** [comment]
> I would prefer if we keep the custom node setup, it still wraps the setup and we don't need to do a bunch of copy/paste, and repeat the wring node version etc

Ok, using a separate action with the updated >v2 caching syntax. Thoughts?

**Comment by jleach** [comment]
@cvarjao Thoughts on the final changes?

**Review by cvarjao — APPROVED** [review]

**Pull request merged**
