### PR TITLE
chore: publish oca pkg to npmjs.org

### PR DESCRIPTION
**Pull request by jleach**
# Summary of Changes

Use lerna to publish `@hyperledger/aries-oca` package with an `alpha` tag with the versioning pattern denoted below. A alpha release will be triggered manually by `workflow_dispatch`.

- 1.0.0-alpha.1
- 1.0.0-alpha.2
- 1.0.0-alpha.3
- ...

Package versions can be incremented by updating the repo tag and version in the `learna.json` file. To reset to a specific version this command can do it for all publishable packages:

```console
npx lerna version 0.0.0 --signoff-git-commit --sign-git-commit --no-private
```

It will create a commit tag `v0.0.0` in this case with the git command `git tag v0.0.0 -m "v0.0.0"` the `-m` option is important (ask me how I know). Without it, the tag will not be recognized. This tag cam be moved around with `git tag v0.0.0 -m "v0.0.0" SHA256` as needed.

To see what lerna will do for the next publication version run:

```console
npx lerna publish --no-private --loglevel=verbose --canary "major" --dist-tag alpha --force-publish
```

Adjust the `--canary "major"` option as needed.

# Related Issues

Please reference here any issue #'s that are relevant to this PR, or simply enter "N/A" if this PR does not relate to any existing issues.

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Comment by jleach** [comment]
@amanji @cvarjao Any preference on our initial version strategy? I have it as `0.0.1` but `0.1.0` is another reasonable
 option. Also, I need to put a `v0.0.0` tag somewhere in the tree as a placeholder for lerna to start from. Was going to place it now but I can go back to when `packages/oca` was last changed.

**Comment by amanji** [comment]
I'd start with a minor prerelease tag similar to how AFJ does it. Once its ready for full consumption with tests, etc we can release a major version.

**Comment by cvarjao** [comment]
I would suggest starting with `1.0.0` as recommended by npm semantic versioning guide:

https://docs.npmjs.com/about-semantic-versioning

I find that anything bellow `1.0.0` has a slightly different version resolution.

**Comment by amanji** [comment]
If you're going to use a major version please use a prerelease tag to indicate that is is still in development.

**Comment by amanji** [comment]
We may want to consult the guide at https://semver.org

Specifically [Item 4](https://semver.org/#spec-item-4)

> 4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

I would consider this very much a work in progress.

The [FAQ](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase) might also help guide the strategy here.

**Comment by amanji** [comment]
Accidentally deleted my previous comment but just to restate:

If we plan to tag this as a major version please use a prerelease tag to indicate that is is still in development.

**Review by amanji — DISMISSED** [review]

**Review by MosCD3 — DISMISSED** [review]

**Comment by jleach** [comment]
@amanji @cvarjao So `1.0.0-alpha.1` for now until we decide to release it?

**Review by amanji — APPROVED** [review]

**Pull request merged**
