### PR TITLE
feat: load remote OCA bundle 

### PR DESCRIPTION
**Pull request by thiagoromanos**
# Summary of Changes

Replace this text with a high-level summary of the changes included in this PR.

# Related Issues

#676 

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [X] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [X] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [] Updated documentation as needed for changed code and new or modified features;
- [X] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Review by amanji — CHANGES_REQUESTED** [review]
Hi @thiagoromanos. Great work on this! The community discussed and agreed that cleaning up some up the types and logic used in the current OCA resolver is warranted (I've actually authored some code to reflect this). We may want to discuss about having that merged in with this or the remote resolver should remain within Bifold until the new classes are in. Happy to chat. I'll submit my PR today so you can see where we are going.

**Comment by thiagoromanos** [comment]
> Hi @thiagoromanos. Great work on this! The community discussed and agreed that cleaning up some up the types and logic used in the current OCA resolver is warranted (I've actually authored some code to reflect this). We may want to discuss about having that merged in with this or the remote resolver should remain within Bifold until the new classes are in. Happy to chat. I'll submit my PR today so you can see where we are going.

Hi @amanji , just called you on discord to discuss that.

**Comment by jleach** [comment]
@thiagoromanos All the other OCA stuff is from @amanji is in. Anything to do on this one still?

**Comment by thiagoromanos** [comment]
> @thiagoromanos All the other OCA stuff is from @amanji is in. Anything to do on this one still?

Actually there is still some work here. As I see, @amanji commit just defines the interfaces and types for the OCA package, but not the implementation of the resolver. So, what I must do now is to import the dependency into the bifold package (and refactor all the oca references), and then implement the extra remote resolver. I gonna have to rewrite most of this PR's code, but it will be a lot cleaner after that.

**Comment by thiagoromanos** [comment]
Gonna open another pull request for this. It will be easier to resolve the conflicts since this branch hasn't been updated for a while.

**Pull request closed without merging**
