### PR TITLE
fix: modal scroll adjustment

### PR DESCRIPTION
**Pull request by CarolineLCa**
# Summary of Changes

Common Remove Modal scrollview adjustment to support more text.

Captura de Tela 2023-05-03 às 15 58 04

# Related Issues

 N/A 

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Review by thiagoromanos — COMMENTED** [review]
That's a small fix which will enhance usability of that screen. LGTM

**Review by bryce-mcmath — APPROVED** [review]

**Comment by bryce-mcmath** [comment]
@CarolineLCa can we get this branch up to date with the base branch so we can get this merged in?

**Comment by jleach** [comment]
@CarolineLCa @thiagoromanos I'm reworking the modals to look like modals and not screens as part of #746. We able to re-do this change to the new modals once they are in place. Currently the PR is waiting for review.

**Comment by jleach** [comment]
@CarolineLCa @thiagoromanos The new modals are in place. This one won't apply any more because the old file is gone.

**Comment by CarolineLCa** [comment]
Okay @jleach, thanks!
I'm closing this one then.

cc: @thiagoromanos

**Pull request closed without merging**
