### PR TITLE
Integrate Redux with Bifold

### PR DESCRIPTION
**Pull request by MosCD3**
# Summary of Changes

- Integirated Redux and Redux-Thunk to the project to allow further scalability
- Used Redux store for user passcode creation and further sign in which could be modified to more complex auth system
- Fixed a bug where the app crashed if pass code mismatch

# Related Issues

Please reference here any issue #'s that are relevant to this PR, or simply enter "N/A" if this PR does not relate to any existing issues.

# Pull Request Checklist

This is just a reminder about the most common mistakes. Please make sure that you tick all _appropriate_ boxes. But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [ ] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this).
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components.
- [ ] Run prettier: `npm run style-format`
- [ ] Updated **documentation** for changed code and new or modified features.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Comment by jleach** [comment]
Is Redux still a thing? I though it was more common how to use hooks + a reducer on a context? `useContext`?
https://github.com/bcgov/bc-wallet-mobile/blob/main/src/Store.tsx
https://github.com/bcgov/bc-wallet-mobile/blob/main/src/Reducer.ts

**Comment by JamesKEbert** [comment]
I can communicate that there's a Redux Store package in the [AFJ-extensions repo](https://github.com/hyperledger/aries-framework-javascript-ext). There's also a React Hooks package that Bifold currently uses, which definitely heads in the direction you were referencing @jleach, and is where my preference lies. Also using hooks allows Bifold to be able to adapt to new and different projects easier and could provide the simplest starting point. I'm definitely open to discussing here further and/or in the Bifold UG call though!

**Comment by MosCD3** [comment]
I believe a redux store that manages the app state might be useful in general not specifically what's related to underlaying Aries hooks or redux store.
If you look at the code, I managed to integrate the "login" or the authentication to be saved in a public store that's not part of the hooks or the AFJ redux library
Remember that this is a "base" app for much bigger and complex application that might have lots of other components. Having a global redux store might come in handy to scale up the app
Any way this is just a "suggestion" .. if no body agrees will close the PR

**Comment by MosCD3** [comment]
not compatible with community suggestions

**Pull request closed without merging**
