### PR TITLE
feat: Refactor the view of Home screen content by adding a SVG image and additional test message

### PR DESCRIPTION
**Pull request by jian4on**
# Summary of Changes

The HomeFooterView component was changed, the home-center-img added to the screen center with additional message "Scan an offer to add a card to your wallet"

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [ ] Updated documentation as needed for changed code and new or modified features;
- [ ] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Review by bryce-mcmath — DISMISSED** [review]

**Comment by bryce-mcmath** [comment]
@jian4on approved but conflicts need to be resolved

**Review by bryce-mcmath — DISMISSED** [review]

**Comment by bryce-mcmath** [comment]
@jian4on a couple more PRs have been merged today, I tried rebasing this one but it looks like there's a bit more conflicts unfortunately

**Comment by jeznorth** [comment]
Please resolve conflicts.

**Review by bryce-mcmath — APPROVED** [review]
Nice work!

**Pull request merged**
