### PR TITLE
feat: update AFJ 0.4.0 branch

### PR DESCRIPTION
**Pull request by AlexanderShenshin**
This PR contains some updates for AFJ 0.4.0 branch:
- Merged changes from main
- Updated AFJ and Shared Components packages, fixed TS errors

@TimoGlastra ^

### CODE REVIEW

**Comment by TimoGlastra** [comment]
Wohoo! Thanks @AlexanderShenshin, It seems there's issues with DCO though.. Can we ignore those for now?

Is it ready for review?

**Review by TimoGlastra — APPROVED** [review]

**Comment by AlexanderShenshin** [comment]
Yea, DCO seems to be broken in some strange way, even for commits from main branch. 
I will take a look and try to fix this before we merge this PR, as it will probably be in draft for some time.

I'm leaving this in draft for now as I encountered CMake related errors when trying to run the app on Android with new versions of Shared Components packages.

Error related to `anoncreds-react-native` package (but there are similar errors for Askar and Indy VDR):
```
Execution failed for task ':hyperledger_anoncreds-react-native:buildCMakeDebug[arm64-v8a]'.
> Build command failed.
  Error while executing process C:\Users\Admin\AppData\Local\Android\Sdk\cmake\3.22.1\bin\ninja.exe with arguments {-C D:\src\oss\aries-mobile-agent-react-native\packages\legacy\app\node_modules\@hyperledger\anoncreds-react-native\android\.cxx\Debug\6z5f5o29\arm64-v8a anoncredsreactnative}
  ninja: Entering directory `D:\src\oss\aries-mobile-agent-react-native\packages\legacy\app\node_modules\@hyperledger\anoncreds-react-native\android\.cxx\Debug\6z5f5o29\arm64-v8a'

  ninja: error: '../../../../build/third-party-ndk/hermes/jni/arm64-v8a/libhermes.so', needed by '../../../../build/intermediates/cxx/Debug/6z5f5o29/obj/arm64-v8a/libanoncredsreactnative.so', missing and no known rule to make it
```

Btw, I'm building the app on Windows, so it might be some platform specific problem.

@blu3beri, maybe you have some thoughts about possible reason?
Just in case, I already applied changes to `build.gradle` file that were mentioned in Askar PR: https://github.com/hyperledger/aries-askar/pull/142

**Comment by berendsliedrecht** [comment]
@AlexanderShenshin anoncreds has a dev.18 release, can you try that one? It says that libhermes is required, but it should also work with JSC IIRC. Otherwise I might have to do some cleanup from the `build.gradle` inside the anoncreds repository.

**Comment by AlexanderShenshin** [comment]
@blu3beri I tried dev.18 release for anoncreds initially and later switched to dev.17 while doing some investigation, but there is the same error.

Just in case, I updated package here.

**Comment by jleach** [comment]
@TimoGlastra @AlexanderShenshin EDIT: Not sure how we can fix the DCO issue. The bot won't let the PR through without it. Maybe it can be fixed during the squash merge.

**Comment by jleach** [comment]
@AlexanderShenshin I think the prob is how the changes from `main` were brought in. For some reason git thinks many of the changes don't exist in `main` but they're clearly here. Because git thinks this PR has 47 commits but most of those are from other people. I wonder if you can checkout `main` and cherry-pick in just your changes. Rebaising might help but could be some work.

**Comment by bryce-mcmath** [comment]
@AlexanderShenshin I second @jleach comment. Should cherry pick the changes that aren't coming from main and rebase / clean up. I don't think there should be 173 files touched

**Comment by TimoGlastra** [comment]
> @AlexanderShenshin I second @jleach comment. Should cherry pick the changes that aren't coming from main and rebase / clean up. I don't think there should be 173 files touched

Note that this PR merged into the `feat/upgrading-to-AFJ-040` and not the main branch. The feat branch hasn't been updated with main for a while, and this PR does that. So all the commits here are already in main, and it's to update the feature branch with the commits from main

**Comment by TimoGlastra** [comment]
I'm going to pull it in locally

**Comment by TimoGlastra** [comment]
Merging locally seems to have done the trick, and it now just shows 3 commits instead of all of them. Thanks @AlexanderShenshin!

**Comment by berendsliedrecht** [comment]
@AlexanderShenshin can you try it with anoncreds 0.1.0-dev.19? If that works I will create the same fix for aries-askar and indy-vdr.

**Comment by AlexanderShenshin** [comment]
@blu3beri Thank you!
I tried to run everything with anoncreds 0.1.0-dev.19 and downgraded Askar and Indy VDR packages (to not get the same error from these).
Anoncreds fix seems to be working, I was able to build and install the app on Android. 

When trying to actually run the app I got another error related to `@aries-framework/anoncreds`:
```
info Opening the app on Android...
TypeError: Cannot read properties of undefined (reading 'configurations')
    at Object.dependencyConfig (D:\src\oss\aries-mobile-agent-react-native\packages\legacy\app\node_modules\@react-native-community\cli-platform-ios\build\config\index.js:102:37)
    at D:\src\oss\aries-mobile-agent-react-native\node_modules\@react-native-community\cli-config\build\loadConfig.js:35:61
    at Array.reduce (<anonymous>)
    at getDependencyConfig (D:\src\oss\aries-mobile-agent-react-native\node_modules\@react-native-community\cli-config\build\loadConfig.js:31:51)
    at Object.get @aries-framework/anoncreds [as @aries-framework/anoncreds] (D:\src\oss\aries-mobile-agent-react-native\node_modules\@react-native-community\cli-config\build\loadConfig.js:79:20)
    at warnAboutManuallyLinkedLibs (D:\src\oss\aries-mobile-agent-react-native\packages\legacy\app\node_modules\@react-native-community\cli-platform-android\build\link\warnAboutManuallyLinkedLibs.js:39:43) 
    at displayWarnings (D:\src\oss\aries-mobile-agent-react-native\packages\legacy\app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:82:44)
    at Object.runAndroid [as func] (D:\src\oss\aries-mobile-agent-react-native\packages\legacy\app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:97:3)
    at Command.handleAction (D:\src\oss\aries-mobile-agent-react-native\node_modules\@react-native-community\cli\build\index.js:108:23)
    at Command.listener [as _actionHandler] (D:\src\oss\aries-mobile-agent-react-native\node_modules\@react-native-community\cli\node_modules\commander\lib\command.js:482:17)
```

But I think it may be more specific issue with compatibility and AFJ version.

**Comment by TimoGlastra** [comment]
This error seems unrelated to AFJ or AnonCreds RS

**Comment by AlexanderShenshin** [comment]
Well, it's possible that this is some local problem. But I noticed that call stack in the error points to `@aries-framework/anoncreds` specifically.

**Pull request merged**
