### PR TITLE
docs : design proposal document for verifier functionality in Aries Mobile Agent

### PR DESCRIPTION
**Pull request by Artemkaaas**
# Summary of Changes

This PR includes the proposed design document covering adding Verifier functionality in Aries Mobile Agent.
For some aspects, provided multiple options to choose which one will be included in the final design and implemented.

# Related Issues

BC Wallet Issue: https://github.com/bcgov/bc-wallet-mobile/issues/800

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [ ] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Comment by jleach** [comment]
I think it would be easier to have a conversation if this were an issue rather than a PR. For example we want to discuss Options 1-3 in an Issue and the final decision to be part of the PR. But, its here now so we'll roll with it. Would also be a bit easier to read the MD as it would be rendered in the UI.

**Comment by jleach** [comment]
In some previous conversations we talked about how to better organize Bifold so different components can be override easily. The initial work is being done as part of PR #641. This will restructure the project so we can start moving some things into their own npm packages. I think it would be good if the deliverable for this matched that pattern as best as possible. 

With that said, I think a little of Option 1 & 3. We could hard-code some samples in JSON along with an interface in TypeScript in its own `npm` package and import what we need into Bifold. Thoughts?

As a minimum, the following should go into its own NPM package:

- proof templates

As a nice to have, this could go into the same submodule:

- screens;
- tightly coupled components.

**Comment by Artemkaaas** [comment]
> I think it would be easier to have a conversation if this were an issue rather than a PR. For example we want to discuss Options 1-3 in an Issue and the final decision to be part of the PR. But, its here now so we'll roll with it. Would also be a bit easier to read the MD as it would be rendered in the UI.

I agree but the next community call will be only on Mar 14  which long far away. Also, I think it will be more productive if interested people read it in advance and form their opinion. 
If we can meet early it will be super cool.

**Comment by Artemkaaas** [comment]
> In some previous conversations we talked about how to better organize Bifold so different components can be override easily. The initial work is being done as part of PR #641. This will restructure the project so we can start moving some things into their own npm packages. I think it would be good if the deliverable for this matched that pattern as best as possible.
> 
> With that said, I think a little of Option 1 & 3. We could hard-code some samples in JSON along with an interface in TypeScript in its own `npm` package and import what we need into Bifold. Thoughts?
> 
> As a minimum, the following should go into its own NPM package:
> 
> * proof templates
> 
> As a nice to have, this could go into the same submodule:
> 
> * screens;
> * tightly coupled components.

This makes sense. We can extract verifier-related logic into the independent package as much as we can. But it is unlikely that we will be able to put screens there right now as they depend on the components currently defined in the core module (so we need to get some package with shared components first.). 
Also, what is the timeline for this re-organization initiative? 
When do we expect to get this PR merged and get lerna configured as well?

**Comment by bryce-mcmath** [comment]
LGTM, I will approve once branch is up to date with main branch

**Comment by Artemkaaas** [comment]
@jleach I actualized the document.

**Review by jleach — APPROVED** [review]

**Comment by jleach** [comment]
@artemkaaas Needs update with base branch. You can enable a feature when you clone so that I or other maintainers can do this if there are no conflicts.

**Comment by jleach** [comment]
@Artemkaaas Able to update one last time and we'll merge in our morning. There is a setting you can change in your fork to allow us to do this. Not required, just a FYI.

**Pull request merged**
