### PR TITLE
chore: add Dependabot configuration

### PR DESCRIPTION
**Pull request by WadeBarnes**
- Configure Dependabot to automatically maintain dependencies for GitHub Actions.
  - Check for updates once a week.
  - Group all updates into a single PR.

### CODE REVIEW

**Comment by MosCD3** [comment]
I am a bit hesitant when it comes to "group all PRs in one PR", this will not work when different PRs from different contributors needs to be reviewed, unless am not getting the correct meaning

**Review by MosCD3 — CHANGES_REQUESTED** [review]
I am a bit hesitant when it comes to "group all PRs in one PR", this will not work when different PRs from different contributors needs to be reviewed, unless am not getting the correct meaning. Can you elaborate more on that?

**Comment by WadeBarnes** [comment]
This only impacts Dependabot updates to GitHub actions.  If you are familiar with Dependabot you'll know that by default it will open a separate PR for each update it identifies.  While this is what you want in most cases for most programming languages, it can cause unnecessary overhead and complications when it comes to updating the actions in GitHub workflows.

Here is an example PR opened by Dependabot based on the exact same configuration I submitted to ACA-Py ([dependabot.yml](https://github.com/hyperledger/aries-cloudagent-python/blob/a7c022a78a0e4f374a7e4a48a99dfa5fdc350e8b/.github/dependabot.yml#L1-L14)):
- https://github.com/hyperledger/aries-cloudagent-python/pull/2784

**Comment by MosCD3** [comment]
> This only impacts Dependabot updates to GitHub actions. If you are familiar with Dependabot you'll know that by default it will open a separate PR for each update it identifies. While this is what you want in most cases for most programming languages, it can cause unnecessary overhead and complications when it comes to updating the actions in GitHub workflows.
> 
> Here is an example PR opened by Dependabot based on the exact same configuration I submitted to ACA-Py ([dependabot.yml](https://github.com/hyperledger/aries-cloudagent-python/blob/a7c022a78a0e4f374a7e4a48a99dfa5fdc350e8b/.github/dependabot.yml#L1-L14)):
> 
> * [chore(deps): Bump the all-actions group with 10 updates aries-cloudagent-python#2784](https://github.com/hyperledger/aries-cloudagent-python/pull/2784)

Cool, thanks for the info, sounds good to me

**Review by MosCD3 — APPROVED** [review]

**Pull request merged**
