### PR TITLE
fix: verifier notifications

### PR DESCRIPTION
**Pull request by wadeking98**
# Summary of Changes

Previously I removed mobile verifier notifications in the home screen. This change adds them back in as well as fixes bugs while viewing or deleting the notification.
image
image

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Review by bryce-mcmath — COMMENTED** [review]
Can we look at where that metadata is being set and try and fix the flow there rather than use a setTimeout?

**Comment by wadeking98** [comment]
> Can we look at where that metadata is being set and try and fix the flow there rather than use a setTimeout?

Yes I've been trying that but I can't seem to resolve the issue. The code to set the metadata is being called, and I can confirm that the record is updated, but for some reason it gets reset/overwritten or maybe ignored by the notification list. I've tried looking at all places where the metadata is written on the proof record and none of them should interfere with writing `details_seen: true`. The funny thing is the same code works for setting the meta data when viewing the actual notification. If I go to the proofDetails screen via actually viewing the notification then the meta data is set correctly, but if I go to the same screen from the mobile verifier screen then the metadata is never set from the notification list's perspective. There's some weird race condition going on with the order the proofRecord is added to the notification list, and when it's metadata is updated.

I could spend some more time working on it to pin down the issue, it would probably take another work day, or I could make a ticket and come back to fixing it later.

I'll let @cvarjao and @jleach chime in too

**Comment by wadeking98** [comment]
@bryce-mcmath I was able to fix it without using the setTimeout

**Review by bryce-mcmath — DISMISSED** [review]
Beauty, well done

**Review by bryce-mcmath — APPROVED** [review]

**Pull request merged**
