### PR TITLE
fix: goal_code for oob connections

### PR DESCRIPTION
**Pull request by jcdrouin21**
# Summary of Changes

This PR fix a problem related to the goal_code. Following the modification of [PR 955 ](https://github.com/hyperledger/aries-mobile-agent-react-native/pull/955) the behavior of the goal_code no longer works for our oob connections with `goal_code: "aries.vc.issue"` or `goal_code: "aries.vc.verify"`. Even with the goal_code we end up in the chat page.

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Comment by jcdrouin21** [comment]
@wadeking98 can you make sure that the PR works with what you wanted to accomplish in [PR 955]((https://github.com/hyperledger/aries-mobile-agent-react-native/pull/955))

**Review by wadeking98 — APPROVED** [review]

**Comment by wadeking98** [comment]
I believe these changes are already in main: https://github.com/hyperledger/aries-mobile-agent-react-native/blob/1f2c4677ab009ef4b8e444e0d295e7d25bc11e8b/packages/legacy/core/App/screens/Connection.tsx#L147

https://github.com/hyperledger/aries-mobile-agent-react-native/blob/1f2c4677ab009ef4b8e444e0d295e7d25bc11e8b/packages/legacy/core/App/screens/Connection.tsx#L167

**Comment by bryce-mcmath** [comment]
After this change, does a wallet to wallet connection invitation still take both wallets to the chat screen?

**Review by wadeking98 — CHANGES_REQUESTED** [review]
After this change the connection inviter will not be redirect to the chat screen only the connection invitee. The oob record is only defined for the person receiving the invitation, but not for the person sending the invitation, so they won't be redirected to the chat screen

**Comment by wadeking98** [comment]
> After this change the connection inviter will not be redirect to the chat screen only the connection invitee. The oob record is only defined for the person receiving the invitation, but not for the person sending the invitation, so they won't be redirected to the chat screen

Upon testing this, it turns out that the person who created the invitation now has access to the oob record as well. both wallets are still redirected to the connection screen after this change

**Review by wadeking98 — APPROVED** [review]

**Pull request merged**
