### PR TITLE
feat: updated qr code scanner to work with ios

### PR DESCRIPTION
**Pull request by sabejensen**
Signed-off-by: seajensen <seajensen@gmail.com>

# Summary of Changes

Modified QR code scanner to recognize QR codes using iOS. Changed function called on QR code scan.

# Related Issues

N/A

# Pull Request Checklist

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this).
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components.
- [x] Run prettier: `npm run style-format`
- [x] Updated **documentation** for changed code and new or modified features.

### CODE REVIEW

**Comment by JamesKEbert** [comment]
Thanks for your efforts here @seajensen! It appears that Prettier is failing though, could you revise that by running `npm run style-format` and pushing another commit to this PR?

**Review by karimStekelenburg — DISMISSED** [review]
Looking good!

**Comment by karimStekelenburg** [comment]
@JamesKEbert regarding the linting... Is it an idea to add a pre-commit hook to avoid this in the future?

**Comment by JamesKEbert** [comment]
> regarding the linting... Is it an idea to add a pre-commit hook to avoid this in the future?

I fully agree that we should add this.

**Comment by karimStekelenburg** [comment]
> > regarding the linting... Is it an idea to add a pre-commit hook to avoid this in the future?
> 
> I fully agree that we should add this.

Solid, I'll try to look into it ASAP and issue a PR!

**Review by manghuli — APPROVED** [review]

**Review by JamesKEbert — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
