### PR TITLE
feat: enable connection invites using shortened urls

### PR DESCRIPTION
**Pull request by thiagoromanos**
# Summary of Changes

This change enables connections using a url shortener request (see [https://github.com/hyperledger/aries-rfcs/tree/main/features/0434-outofband#url-shortening](https://github.com/hyperledger/aries-rfcs/tree/main/features/0434-outofband#url-shortening)).
To receive invites using a url shortener, I changed the call `agent?.oob.parseInvitation(uri)` to `agent?.oob.parseInvitationShortUrl(uri)`. They are basically the same, but the second one also has support to short urls. 

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [X] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [X] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [X] Updated documentation as needed for changed code and new or modified features;
- [X] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Comment by cvarjao** [comment]
Can you help me understand why we need to have an allow list of short URL domains? or am I misunderstanding it? I am wondering if there is another way to identify based on `c_i`/`d_m` parameters or some other way.

**Comment by thiagoromanos** [comment]
> Can you help me understand why we need to have an allow list of short URL domains? or am I misunderstanding it? I am wondering if there is another way to identify based on `c_i`/`d_m` parameters or some other way.

The "url list" was a way I thought to know which ones are redirects and which are short urls. My idea was to, knowing the address I hosted my url shortener, I could tell the application to receive an invite instead of a redirect.
Looking into the code of aries-framework-javascript, [on the parseInvitation.ts file](https://github.com/hyperledger/aries-framework-javascript/blob/7be979a74b86c606db403c8df04cfc8be2aae249/packages/core/src/utils/parseInvitation.ts#L97), I noted that it checks if its out-of-band (`oob`) or an connection invitation (`c_i`, `d_m`), otherwise it considers an oob invitation from short url. Since the bifold checks if it is an redirect, I can't see other way to check short urls.
Is there any way to improve this solution? I'm out of ideas right now.

**Comment by jleach** [comment]
@thiagoromanos Roughly paraphrasing @amanji here but he remarked that as per the OOB spec,  if a URL does not have the `c_i` or `d_m` query params then its a redirect. It looks like AFJ distinguishes between redirects and short URLs. @amanji thoughts on what to do? Opportunity to cleanup some code?


```
/**
 * Parses URL containing encoded invitation and returns invitation message. Compatible with
 * parsing short Urls
 *
 * @param invitationUrl URL containing encoded invitation
 *
 * @param dependencies Agent dependicies containing fetch
 *
 * @returns OutOfBandInvitation
 */
export const parseInvitationShortUrl = async (
  invitationUrl: string,
  dependencies: AgentDependencies
): Promise<OutOfBandInvitation> => {
  const parsedUrl = parseUrl(invitationUrl).query
  if (parsedUrl['oob']) {
    const outOfBandInvitation = OutOfBandInvitation.fromUrl(invitationUrl)
    return outOfBandInvitation
  } else if (parsedUrl['c_i'] || parsedUrl['d_m']) {
    const invitation = ConnectionInvitationMessage.fromUrl(invitationUrl)
    return convertToNewInvitation(invitation)
  } else {
    try {
      return oobInvitationFromShortUrl(await fetchShortUrl(invitationUrl, dependencies))
    } catch (error) {
      throw new AriesFrameworkError(
        'InvitationUrl is invalid. It needs to contain one, and only one, of the following parameters: `oob`, `c_i` or `d_m`, or be valid shortened URL'
      )
    }
  }
}
```

**Comment by thiagoromanos** [comment]
@jleach and @cvarjao, I updated the PR with an update that might be better than my previous solution. Knowing that `parseInvitationShortUrl` will check for connection invites in the GET parameter of the url (`c_i`, `d_m` or `oob`) or shortened urls invites, and if it isn't one of those it throws an error, I used the `catch` block from `handleInvitation` to handle redirects. If this also fails, then a BifoldError is thrown.

**Review by jleach — APPROVED** [review]
Tested. Seems to be working fine. Nice work!

**Pull request merged**
