### PR TITLE
Auto organize imports

### PR DESCRIPTION
**Pull request by jleach**
# Summary of Changes

I find inconsistent imports can cause more merge conflicts and mental effort than should be. How about we get VSCode to manage consistency for us? I've added a `.vscode/settings.json` file with the directive for VSCode to organize imports on save. It will put them in order, remove unused imports, and keep them formatted propertly. 

It's fine if ppl don't use VSCode, those of us using it will have imports organize on save. As the app stabilizes over time I expect imports will change less frequently.

# Related Issues

N/A

# Pull Request Checklist

This is just a reminder about the most common mistakes. Please make sure that you tick all _appropriate_ boxes. But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this).
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components.
- [x] Run prettier: `npm run style-format`
- [x] Updated **documentation** for changed code and new or modified features.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Comment by TimoGlastra** [comment]
I'm a big proponent of this! In AFJ we use the eslint-plugin-import to automatically order imports. As we already have eslint and it is agnostic to the editor being used I think it may also be a good fit for this project. You can take a look at AFJ as an example.


What do you think?

**Comment by jleach** [comment]
@TimoGlastra I'll check it out but it seems unnecessarily complicated to get started and gives lots of edge case problems like:
`   9:33  error    Parse errors in imported module 'react-native': ';' expected. (14:32)  import/namespace`

Also, it does not seem to fix the issues automatically like VSCode which is nice: Let the machines do the grunt work.

**Comment by jleach** [comment]
@TimoGlastra Ok, a bit of yack shaving there but I think its implemented now.

**Comment by TimoGlastra** [comment]
>  it seems unnecessarily complicated to get started and gives lots of edge case problems like

Feel free to do it like your initial implementation, you're doing the hard work here! In AFJ I find it quite nice because it just removes the burden of organising imports for the developer and you can auto fix it (and we can enforce it in CI).


To auto fix eslint and prettier issues on save you can use the following configuration:

`.vscode/settings.json`

```
{
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  }
}
```	

`.vscode/extensions.json`

```
{
	// List of extensions which should be recommended for users of this workspace.
	"recommendations": [
		"dbaeumer.vscode-eslint"
	]
}
```

**Comment by jleach** [comment]
@TimoGlastra I think it's working now without the `.vscode/settings.json` change. I did add the plug-in recommendations that just seems generally handy. Ready for review.

**Review by TimoGlastra — APPROVED** [review]
Awesome! :)

**Pull request merged**
